### ISSUE TITLE
3.4.1 is out !

### ISSUE THREAD

**Issue by berak** [hybridgroup/gocv#109]
* appveyor script
* roadmap
* version_test.go
* all doclinks lead to 3.4.0 (question here - better reroute to master docs ? or use the existing docstrings from the hpp files (instead of links) (ugly, cluttered with doxygen artefacts & mathjax)?

**Comment by deadprogram** [comment]
The docs links are one of my least favorite formats. So long! Turns out however that just changing the version number in the URL does work, even if it is a bit ugly. I'd love to have a simpler format.

That said, I think it is better to link to the OpenCV docs site than to duplicate all that content into the Go code. That allows us to have control over the GoDocs formatting, but still get back to the full OpenCV docs.

What do you think?

**Comment by berak** [comment]
the last part of the docs url seems to be a md5 hash of the function signature, so it won't change (as long as they can't change signatures due to abi compliance) . not sure, what happens to the https://docs.opencv.org/master/d2/de8/ part, if functions are added, though.

but it's probably a good idea to use "master" instead of a fixed version number with additional prs.

**Comment by deadprogram** [comment]
The `dev` branch now has been updated for OpenCV 3.4.1 in preparation for the next release.

**Comment by deadprogram** [comment]
GoCV v0.10.0 is released, so now closing this issue. Thanks!
