### ISSUE TITLE
Why is Mat used for in Range instead of a scalar wit hsv? And how can I sat Mat to a lower HSV range?

### ISSUE THREAD

**Issue by rdoetjes** [hybridgroup/gocv#1154]
I am trying to filter out a range based on HSV but much to my amazement the upper- and lower bounds in the InRange function in gocv don't take a scalar but a Mat.

Now I am curious how to set the Mat for my lower- and upper bound to an HSV value?

Thanks

**Comment by HIGHER98** [comment]
You could use the [InRangeWithScalar](https://pkg.go.dev/gocv.io/x/gocv#InRangeWithScalar) function instead of the InRange function. 

> how to set the Mat for my lower- and upper bound to an HSV value?

You could create a mat from a scalar and use that. This is what is done in [the Unit Test for InRange function](https://github.com/hybridgroup/gocv/blob/release/core_test.go#L1222):

```go
func TestMatInRange(t *testing.T) {
	mat1 := NewMatWithSize(101, 102, MatTypeCV8U)
	defer mat1.Close()
	lb := NewMatFromScalar(NewScalar(20.0, 100.0, 100.0, 0.0), MatTypeCV8U)
	defer lb.Close()
	ub := NewMatFromScalar(NewScalar(20.0, 100.0, 100.0, 0.0), MatTypeCV8U)
	defer ub.Close()
	dst := NewMat()
	defer dst.Close()
	InRange(mat1, lb, ub, &dst)
	if dst.Empty() {
		t.Error("TestMatAddWeighted dest mat3 should not be empty.")
	}
}

```

**Comment by deadprogram** [comment]
Looks like this question was answered, so now closing. Thank you everyone!
