### ISSUE TITLE
[HelpWanted] More examples with tensorflow DNN models

### ISSUE THREAD

**Issue by denismakogon** [hybridgroup/gocv#157]
Would you mind to help to get the same example as with tensorflow and python 
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API?

**Comment by deadprogram** [comment]
Hi @denismakogon are you referring to https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#run-network-in-opencv specifically?

**Comment by denismakogon** [comment]
Yes, the one running on opencv.

**Comment by deadprogram** [comment]
This branch has an example that does what you are looking for @denismakogon 

https://github.com/hybridgroup/gocv/blob/feature/openvino-ie-support/cmd/dnn-detection/main.go

It requires the upcoming next version of OpenCV 3.4.2+ in order to work correctly.

Please check it out and see what you think.

**Comment by deadprogram** [comment]
This code is now released as part of v0.14.0 so now closing. Thank you!
