### ISSUE TITLE
Unable to compile OpenCV on windows.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [hybridgroup/gocv#165]
I want to use gocv, but I can't compileit. this is issue source: [opencv compile result](https://github.com/opencv/opencv/issues/11288)

**Comment by deadprogram** [comment]
You might need to use the `-DCPU_DISPATCH=` flag for CMake. See: https://github.com/opencv/opencv/pull/10936

**Comment by MiyamuraMiyako** [comment]
@deadprogram Thanks a lot. I compiled successed!

**Comment by cedarmora** [comment]
I also ran into this problem in the [getting started guide](https://gocv.io/getting-started/windows/) and solved it with [this stackoverflow answer](https://stackoverflow.com/a/49975510/3890284), very similar to @deadprogram's solution.

The issue appears to be that CMake thinks that my cpu, the i7-7700hq, is capable of using AVX-512, which it cannot.

Here is how I solved it: After I did the step that said "BUILD_opencv_saliency should be unchecked", in the Cmake utility, I took note of the existing value of CPU_DISPATCH: `SSE4_1;SSE4_2;AVX;FP16;AVX2;AVX512_SKX`. I then removed the existing entry for CPU_DISPATCH, and added another entry for CPU_DISPATCH with the string: `SSE4_1;SSE4_2;AVX;FP16;AVX2`. I only removed `;AVX512_SKX`. Then I continued with the generating and mingw32-make in the [guide](https://gocv.io/getting-started/windows/) and it compiled.

 Could a note be included about this problem in the [getting started guide](https://gocv.io/getting-started/windows/) or something? Or maybe it was fixed in subsequent versions.

**Comment by deadprogram** [comment]
I think we need to add to the docs, and also possibly provide a `.cmd` equivalent to `make install`. Reopening this issue to not lose track of it.

**Comment by cedarmora** [comment]
On a similar note to documentation, right after the `mingw32-make install` step, I had a hard time figuring out that the current directory meant by the command `go run .\cmd\version\main.go` was at GOPATH\src\gocv.io\x\gocv

**Comment by deadprogram** [comment]
I'm currently testing a new script for download install on Windows 10 in the `dev` branch, that will be include in the next release.

**Comment by deadprogram** [comment]
This code and associated docs are now released as part of v0.14.0 so closing this issue. Thank you!
