### ISSUE TITLE
NV12 to RGB CUDA

### ISSUE THREAD

**Issue by deepch** [hybridgroup/gocv#261]
Good afternoon.

I've been watching your source code for a long time, but I still do not understand if I can use it for my task.

Im decode video using goav using h264_cuvid it fast and easy output NV12 frame i have byte array y u v pix, everything would be cool if I did not have to convert this to rgb to work with darknet

Soft processing of frame 5MP takes too much time. I found a solution that opencv knows how to do this on gpu https://github.com/opencv/opencv/blob/master/modules/cudacodec/src/cuda/nv12_to_rgb.cu

can I do this using your project? I just do not understand how.

Thank you for your help.

**Comment by deadprogram** [comment]
Hello @deepch in order to support the cuda functions, you would need to add support for those modules. No work has been started on that yet.

Check out https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#something-you-wantneed-from-opencv-does-not-appear-to-be-in-gocv

We'd love to get a PR adding this functionality!

**Comment by deepch** [comment]
I will very much wait for cuda without it to work very slowly.
