### ISSUE TITLE
Overlay Dynamic Text

### ISSUE THREAD

**Issue by gmonk** [hybridgroup/gocv#307]
## Description
Wondering if it is possible to overlay dynamic text from a chan of strings  or other method with gocv.PutTex ?  I am doing the somthing similar with python but I so far have not found a way with go.  I am simply pulling video from an IP camera feed at a location with a few sensors and based on the sensors that get triggered I would like to overlay that information on the live feed.  Every attempt seems to impact frame rate when trying to display the text.  Only when I change to static text does everthing resume.
## Your Environment

* Operating System and version: Ubuntu 17.10
* OpenCV version used: 3.4.3
* How did you install OpenCV?  build from source
* GoCV version used: 0.16.0
* Go version: 1.10
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? yes

**Comment by deadprogram** [comment]
Hello @gmonk not sure what you mean by "dymanic" text. You need to use `PutText()` https://godoc.org/gocv.io/x/gocv#PutText in order to render text to your window. You probably want to separate the goroutines that display your window and the latest frames, from the goroutine that processes your sensors.

This is a program that is one of the included examples that does a similar thing, but using a DNN to process data which has a slower frame rate than the capture can display:

https://github.com/hybridgroup/gocv/blob/master/cmd/dnn-pose-detection/main.go

Hope that helps!

**Comment by deadprogram** [comment]
OK, cool. Now closing, please reopen if needed.
