### ISSUE TITLE
exit status 3221225781

### ISSUE THREAD

**Issue by zxysilent** [hybridgroup/gocv#38]
i don`t know 
go run main.go
exit status 3221225781

**Comment by MiyamuraMiyako** [comment]
@zxysilent hi,please tell me how to resolve ```exit status 3221225781```.

**Comment by zxysilent** [comment]
Use the latest  mingw .
What I'm using now is  v7.2.0

**Comment by harpy-wings** [comment]
I had the same problem.
Fixed by adding ```C:\opencv\build\install\x64\mingw\bin``` to system path.
as instructed here
"[https://medium.com/@ctpathirana/gocv-installation-in-windows-10-e5b0f1764351](https://medium.com/@ctpathirana/gocv-installation-in-windows-10-e5b0f1764351)"
also using MinGW 7.3.0 produces some other errors on my windows too. using v8.1.0 is fine.

**Comment by chambon** [comment]
did you find something, same problem i have tested many distrib 7.3 8.1 ...following instructions and nothing
 exit status 3221225794 and now exit status 3221225781
i have unistalled ..reinstalled ... whant can i do ..

**Comment by NguyenKyThinh94** [comment]
:(

**Comment by nutsinu** [comment]
In my case on Windows 10 it was a missing libopenblas.dll file. I downloaded openblas binaries and put them in PATH then the script ran flawlessly
