### ISSUE TITLE
Tests failing on macOS

### ISSUE THREAD

**Issue by Sauraus** [hybridgroup/gocv#389]
`make test` on dev & master branches both fails because of a missing file `nonexistent.mp4`, name kind of implies it shouldn't be there but if that's the case the test should pass.

## Description
> [antek@Anteks-MBP]:[~/go/src/gocv.io/x/gocv] (getlayernames)$ make test
go test . ./contrib
--- FAIL: TestMSER (0.15s)
    features2d_test.go:176: Invalid KeyPoint array in MSER test: 232
OpenCV: Couldn't read video stream from file "nonexistent.mp4"
FAIL
FAIL	gocv.io/x/gocv	5.472s
ok  	gocv.io/x/gocv/contrib	0.727s
make: *** [test] Error 1

## Steps to Reproduce
1. cd $GOPATH/src/gocv.io/x/gocv
2. make test

## Your Environment
* Operating System and version:
OS X Mojave
* OpenCV version used:
4.0.0
* How did you install OpenCV?
brew install opencv
* GoCV version used:
dev branch @ 5a0e230
* Go version:
[antek@Anteks-MBP]:[~/go/src/gocv.io/x/gocv] (getlayernames)$ go version
go version go1.11.4 darwin/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
No | `env.sh` says its been deprecated

**Comment by deadprogram** [comment]
Hello @Sauraus that is very interesting. We run the tests on both Linux and WIndows, but do not have a CI setup for macOS. Anyone else able to confirm tests failing on macOS?

**Comment by Sauraus** [comment]
What is the intended test case here? Should the file exist or not?

**Comment by jonathankarsh** [comment]
Hi @Sauraus and @deadprogram,
I'm also running on a mac. It seems that the failure occurs because of the KeyPoint array length in features2d_test.go (line 176). I also get `len(kp) == 232`. If I let this number through the if statement in TestMSER, this test passes.
The missing file `nonexistent.mp4` is OK. This is OpenCV complaining (so we get C++'s log message) but the related test passes. Would be nice to somehow make that message not appear, but not critical IMO.
Please LMK if you think adding `len(kp) == 232` to TestMSER makes sense, we can create a PR and close this issue off.

**Comment by deadprogram** [comment]
Hello, all.

Is this still an issue with the latest versions of GoCV and OpenCV?

**Comment by jonathankarsh** [comment]
I get a failure for OpenCV version (still on 4.0.0), and the same warning message as in the original posting in this issue:
OpenCV: Couldn't read video stream from file "nonexistent.mp4"
-- which as I posted earlier, does not mean a failure.

Is the version test blocking (hiding) other tests?
If not, and it is the only failure then I think the answer to your question is "no". And that we can close this thread.
HTH
