### ISSUE TITLE
suggest to auto gc for go opencv object like python

### ISSUE THREAD

**Issue by fastfading** [hybridgroup/gocv#411]
<img width="542" alt="default" src="https://user-images.githubusercontent.com/8351732/53217228-3abb7680-3692-11e9-802a-ba55d0490297.png">
check the red line , each object resource need to be manual recycled .  
that is c style , not go style.
suggest to use  runtime.SetFinalizer  to audo recycle resource.

```go
func NewMat() Mat {
        mat := newMat(C.Mat_New())
        runtime.SetFinalizer(&mat,func (m *Mat) Close() error ) //auto gc release 
        return mat
}
```
so  user wouldn't need to add defer every time

**Comment by berak** [comment]
unfortunately, there's a problem, your approach does not solve:

most memory in an opencv program is allocated from the c-api , think: "pixels", not at all from go (and the go garbage collector never sees this)

while the current `defer` based solution releases the c-allocated memory at **block** scope (the earliest possible time), your solution will lead to piling up c-allocated memory, the garbage collector won't get triggered at the right time, because the go Mat's are all very small.

**Comment by deadprogram** [comment]
@berak is absolutely correct. It seems appealing but the Golang GC does not guarantee that the behavior does what you want @fastfading please see https://github.com/hybridgroup/gocv/issues/292 for a previous conversation about this topic.

**Comment by deadprogram** [comment]
Closing, reopen if needed. Thanks.
