### ISSUE TITLE
Consider changing Makefile to not automatically install dependencies

### ISSUE THREAD

**Issue by Minnozz** [hybridgroup/gocv#691]
## Description
I believe it is considered bad practice to automatically install system-wide dependencies from a Makefile. The current Makefile [does this](https://github.com/hybridgroup/gocv/blob/master/Makefile#L34) in the default target, even using `sudo`. This surprised me when I ran `make` for the first time.

I believe it would be better if the `deps` target was not included in the [default target](https://github.com/hybridgroup/gocv/blob/master/Makefile#L2). `make deps` could still be available for users who want to use the Makefile to install dependencies, but it should be explicit instead of automatic.

**Comment by timesselens** [comment]
Not only that, but also this https://github.com/hybridgroup/gocv/blob/master/Makefile#L74

I'm baffled. Kudos @Minnozz for keeping it diplomatic. Allow me to be blunt: if you're about to write this utter crap in a Makefile you deserve a slap with a 400lbs unix manual. This has the potential to wipe an entire system, just because you were too lazy to type the actual dir that needs to be removed? Adding sudo for good measure along the way?!

**Comment by deadprogram** [comment]
@timesselens please remain polite or be blocked for violating our code of conduct. Thank you.

**Comment by deadprogram** [comment]
Here is a link to the CoC for your convenience: https://github.com/hybridgroup/gocv/blob/dev/CODE_OF_CONDUCT.md

**Comment by deadprogram** [comment]
Last release included some changes to the `Makefile` for a default task `explain` to reduce any danger from running it unawares: https://github.com/hybridgroup/gocv/blob/dev/Makefile#L20

I am going to close this issue now, please reopen if needed. Thanks @Minnozz  for pointing it out.
