### ISSUE TITLE
Memory leak in IMRead

### ISSUE THREAD

**Issue by agorman** [hybridgroup/gocv#812]
I am using gocv to process a large number of images and I appear to have a memory leak. It looks to be coming from the IMRead function.

## Description
For every IMRead call memory increases by a few megs to 10s of megs.

## Steps to Reproduce

I have a long running process doing this in a loop. The path variable is different for each IMRead call.

~~~
	img := gocv.IMRead(path, gocv.IMReadUnchanged)
	img.Close()
~~~

## Your Environment
Operating System and version: CentOS 7
OpenCV version used: 4.5.1
How did you install OpenCV? from source
GoCV version used: v0.26.0
Go version: go1.15.6
Did you run the env.sh or env.cmd script before trying to go run or go build? No

opencv config options
~~~
PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib64/pkgconfig cmake3 \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=/tmp/build/opencv_contrib-4.5.1/modules \
    -D WITH_IPP=NO \
    -D WITH_1394=NO \
    -D WITH_LIBV4L=NO \
    -D WITH_V4l=YES \
    -D WITH_TBB=YES \
    -D WITH_FFMPEG=YES \
    -D WITH_GPHOTO2=YES \
    -D WITH_GSTREAMER=YES \
    -D INSTALL_C_EXAMPLES=NO \
    -D INSTALL_PYTHON_EXAMPLES=NO \
    -D BUILD_ANDROID_EXAMPLES=NO \
    -D BUILD_DOCS=NO \
    -D BUILD_TESTS=NO \
    -D BUILD_PERF_TESTS=NO \
    -D BUILD_EXAMPLES=NO \
    -D BUILD_opencv_java=NO \
    -D BUILD_opencv_python=NO \
    -D BUILD_opencv_python2=NO \
    -D BUILD_opencv_python3=NO \
    -D BUILD_ANDROID_EXAMPLES=NO \
    -D OPENCV_GENERATE_PKGCONFIG=YES ..
~~~

**Comment by deadprogram** [comment]
Hello @agorman I would need to see more of your code to try to help out. 

GoCV itself is tested using memory profiling as part of the CI tests to ensure that the core wrappers that it provides do not leak any `Mat`. 

See https://github.com/hybridgroup/gocv/blob/release/mat_profile.go for more info.
https://github.com/hybridgroup/gocv/blob/release/.circleci/config.yml#L42 is how the tests are executed using `-tags matprofile` so that the memory profiling in included as part of the test run.

**Comment by agorman** [comment]
You're right, it was something else in my code. Sorry about that and thanks for the great work on this module.
