### ISSUE TITLE
Explain or add something to get HSV pixel value

### ISSUE THREAD

**Issue by metal3d** [hybridgroup/gocv#92]
Hello,

Working on a little project, I need to change saturation of a `gocv.Mat`. At this time, I subsample ROI on on image and used `roi.ConvertTo(working, gocv.ColorBGRToHSV )`

Python returns a big list of tripplet (H, S, V) so we can change a channel, and rebuild Mat. But with gocv I can't find anything to do this.

I tried to understand how to make it with `working.GetIntAt(i, j)` but it's not working as expected (maybe I don't understand what is the Mat)

Rebulding image with `working.ConvertTo(out, MatTypeCV8U)` gives a stange grid, not a saturated image. So... Is there something that exists or gocv lakes of that kind of operation ?

**Comment by deadprogram** [comment]
I have not done anything with HSV in OpenCV myself, but I will look into it.

**Comment by berak** [comment]
hi @metal3d  ;) (mcclintic from #opencv here..)

ConvertTo does not change the colorspace, but the pixel type (say, from uchar to float) , so that'S the wrong function. use:

	hsv := gocv.NewMat()
	gocv.CvtColor(img, hsv, gocv.ColorBGRToHSV)

so, now you have a 3channel, uchar HSV image. in c++, the next step would be, to split() the hsv image into c3 seperate channels, work on the S channel (btw, you'd access it with `GetUCharAt(row,col)`), and later merge() them back again.

unfortunately now, while there is a Mat.Merge() function, it's Split() counterpart is absent (so far !!) 

(that would be my issue, in this context)

@deadprogram , super cool effort !

**Comment by metal3d** [comment]
@berak hello ;)

Ok, you were right, CvtColor correctly transform color type, that was my fault.

And yes, there are 3 channels right now... But as you said, there is no "Split" function. It's in the ROADMAP file... with a lot of array operations that are not implemented :(

So, I will need to pass to python at this time. A pitty for me, but I will not abandon GoCV ;)

**Comment by metal3d** [comment]
@berak I finally found a nice Golang way :) It's maybe wrong but the visual result seems to be ok

```golang

hsv := gocv.NewMat()
gocv.CvtColor(work.Region(r), hsv, gocv.ColorBGRToHSV)
w := gocv.NewWindow("hsv")

// get bytes
b := hsv.ToBytes()

// start at 1 = S channel ?
for i := 1; i < len(b); i += 3 {
	b[i] = 255
}

hsv = gocv.NewMatFromBytes(hsv.Rows(), hsv.Cols(), gocv.MatTypeCV8UC3, b)

// use dst mat to convert HSV to BGR
dest := gocv.NewMat()
gocv.CvtColor(hsv, dest, gocv.ColorHSVToBGR)

w.IMShow(dest)
w.WaitKey(0)

```

**Comment by deadprogram** [comment]
I'll prioritize work on the `Split` function for the next release. Cool work-around!

**Comment by berak** [comment]
just added a pr for this ;)

**Comment by deadprogram** [comment]
This will go out as part of the next release. Thank you!

**Comment by deadprogram** [comment]
Release 0.10.0 is now out, so closing. Thanks!
